name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get install -y libopenmpi-dev openmpi-bin

      - name: Build serial
        run: gcc serial/grid_serial.c -o bin/serial -lm

      - name: Build OpenMP
        run: gcc openmp/grid_openmp.c -fopenmp -o bin/openmp -lm

      - name: Build MPI
        run: mpicc mpi/grid_mpi.c -o bin/mpi -lm

      - name: Run serial (small dataset)
        run: ./bin/serial data/small.txt

      - name: Run OpenMP (small dataset)
        run: OMP_NUM_THREADS=2 ./bin/openmp data/small.txt

      - name: Run MPI (small dataset)
        run: mpirun -np 2 --oversubscribe ./bin/mpi data/small.txt
